-- 委托咨询表
CREATE TABLE IF NOT EXISTS biz_consultation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    consultation_no VARCHAR(50) NOT NULL UNIQUE COMMENT '咨询单号',
    client_company VARCHAR(200) NOT NULL COMMENT '客户公司名称',
    client_contact VARCHAR(50) NOT NULL COMMENT '联系人',
    client_tel VARCHAR(20) NOT NULL COMMENT '联系电话',
    client_email VARCHAR(100) COMMENT '邮箱',
    client_address VARCHAR(500) COMMENT '地址',
    sample_name VARCHAR(200) NOT NULL COMMENT '样品名称',
    sample_model VARCHAR(100) COMMENT '样品型号/规格',
    sample_material VARCHAR(100) COMMENT '样品材质',
    estimated_quantity INT COMMENT '预计样品数量',
    test_items TEXT COMMENT '检测项目列表(JSON格式)',
    test_purpose VARCHAR(50) DEFAULT 'other' COMMENT '检测目的: quality_inspection-质量检验, product_certification-产品认证, rd_testing-研发测试, other-其他',
    urgency_level VARCHAR(20) DEFAULT 'normal' COMMENT '紧急程度: normal-普通, urgent-紧急, very_urgent-非常紧急',
    expected_deadline VARCHAR(50) COMMENT '期望完成时间',
    client_requirements TEXT COMMENT '客户特殊要求',
    budget_range VARCHAR(100) COMMENT '预算范围',
    status VARCHAR(20) DEFAULT 'following' COMMENT '状态: following-跟进中, quoted-已报价, rejected-已拒绝, closed-已关闭',
    follower VARCHAR(50) COMMENT '跟进人',
    follower_id BIGINT COMMENT '跟进人ID',
    follow_up_records TEXT COMMENT '跟进记录(JSON格式)',
    feasibility VARCHAR(20) COMMENT '可行性评估: feasible-可行, difficult-困难, infeasible-不可行',
    feasibility_note TEXT COMMENT '可行性说明',
    estimated_price BIGINT COMMENT '预估价格(分)',
    quotation_id BIGINT COMMENT '关联的报价单ID',
    quotation_no VARCHAR(50) COMMENT '关联的报价单号',
    attachments TEXT COMMENT '附件信息(JSON格式)',
    created_by VARCHAR(50) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted INT DEFAULT 0 COMMENT '逻辑删除: 0-正常, 1-已删除',
    INDEX idx_consultation_no (consultation_no),
    INDEX idx_client_company (client_company),
    INDEX idx_status (status),
    INDEX idx_follower (follower),
    INDEX idx_create_time (create_time),
    INDEX idx_quotation_no (quotation_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='委托咨询表';
